export const STRINGS = {
  about: 'About',
  aboutDescription: `Six months ago, a group of women came together and decided to work on balancing gender inequality within crypto.

  Today, the Surge Passport is your golden ticket to Web3. It is designed strategically to serve both as a point of entry and an accelerator to your Web3 development. And the art is BEAUTIFUL, of course!

  With the Passport, you get access to educational courses, scholarships, mentorships, discounts, digital tools, subscriptions, IRL experiences… <strong>and this is just the beginning.</strong>
  `,
  aboutCollection: 'About the Collection',
  aboutSurge: 'About Surge',
  aboutSurgeDescription: `Surge is a female-led organization, educating and securing womxn's place in Web3.

  To do so, we operate as creators of original educational content, curators of existing media, facilitators of Web3 careers for community members, and partners to mission-aligned Web3 platforms.

  Surge’s ultimate goal is to tie together an enhanced ecosystem of compensated opportunities for women in Web3, by working with other mission-aligned organizations.
  `,
  checkOutCollection: 'Check out the collection',
  clickToMint: 'Click to Mint',
  connectedAccount: 'Connected account: ',
  connectWallet: 'Connect Wallet',
  connectWalletToMint: 'Connect wallet to mint',
  crossmintDisclaimer: 'Incurs a 4.5% fee and you will only be able to mint 1 at a time. Then, you can export your NFT to a crypto wallet (for free) and claim perks!',
  createAWallet: 'Don\'t have a one? Create a Metamask wallet',
  dontHaveAWallet: 'Don\'t have a wallet? Create one here',
  ethMint: 'Mint with ETH',
  errorBadAddress: 'Your transaction did not go through. This could be either because the address you added is not a real one, you or your friend have already minted 5, or you don\'t have enough funds.',
  findYourTxn: 'You can find your transaction on Etherscan here',
  finishedAndMintingFriend: 'Already minted yours? Gift to a friend 🎁',
  frequentlyAskedQuestions: 'Frequently Asked Questions',
  friendETHAdress: 'Your friend\'s ETH address',
  faq: 'FAQ',
  giftPassport: 'Gift Passport',
  giftToFriend: 'Gift a Surge Passport NFT to a friend',
  helpOnboard: 'Help onboard more womxn into Web3 by gifting them a Passport.',
  hiddenNFT: 'Since this will be an airdrop, please alert your friend that the Surge Passport NFT may appear in their \'hidden\' folder within OpenSea. Make sure it\'s the<a href = "https://opensea.io/collection/surge-passport"> right collection</a> when they \'unhide\' it.',
  howManyPassport: 'How many passports   do you want to mint?',
  howToMint: 'How to mint?',
  learnMoreAboutSurge: 'LEARN MORE ABOUT SURGE',
  logOut: 'Log out',
  mint: ' mint?',
  mintActive: 'mint',
  mint1NFT: 'Mint 1 NFT for your friend',
  mint1ForFriend: 'Mint 1 NFT directly to your friend\'s address!',
  mintETH: 'Connect your wallet to mint up to 5 NFTs with ETH at the same time (and save up on gas). You\'ll immediately have access to claim all perks!',
  mintForAFriend: 'Mint and airdrop a Surge Passport to a friend! 🎁',
  mintingSuspense: 'Minting taking place',
  mintWait: 'Minting happening right now. Will let you know once the transaction goes through.',
  mintingMeans: `Minting means registering the NFT as a token in the blockchain. The Surge Passport is a collection of 5,000 NFTs built through our generative art algorithm. The moment you click “mint” we generate one for you and transfer it to your address so you´re the owner and can start accessing all the perks`,
  mintPassport: 'Mint Surge Passport NFT',
  mintSuccess: 'Minting successful! Transaction id:',
  nftPriceFriend: '1 NFT is 0.08 ETH, but you\'ll need a bit more to pay for gas.',
  nftPrice: 'Each NFT is 0.08 ETH, but you\'ll need a bit more to pay for gas.',
  onlyAvailablePublicSale: 'This option is only available during Public Sale, which starts on April 30th.',
  openSeaCollectionDomain: 'https://opensea.io/collection/surge-passport',
  ourPartners: 'Our Partners',
  passportPerks: 'Passport Perks',
  passportPerksDescription: 'Here are some of the amazing goodies you get when you own the Surge Passport NFT',
  perks: 'Perks',
  presaleOpens: 'Presale mint opens April 28th',
  presaleNotOpen: 'Presale is not open.',
  publicSaleNotActive: 'Paying with credit card will be enabled only for public sale, starting April 30th, and will incur a 4.5% processing fee. Then, you\'ll be able to export it (for free) to a wallet to claim perks.',
  publicSaleNotOpen: 'Public sale is not open.',
  roadmap: 'Roadmap',
  roadmapUpdate: 'Get the latest updates on our roadmap',
  browser: 'Unsupported browser 👀',
  browserNotSupported: 'The browser you\'re using is not supported. Please connect using Chrome, Firefox, or Metamask\'s browser for a better experience.',
  securingWomen: 'Securing women’s place in Web3',
  seePerks: 'SEE PERKS',
  soldOut: 'Collection is sold out, but you can still buy an NFT on OpenSea.',
  soldOutCaption: 'The Surge Passport NFT collection is sold out, but you can still purchase through <a href={STRINGS.openSeaCollectionDomain}>OpenSea</a>.',
  stepByStep: 'Step by step',
  surgeCollectionDescription: 'Each Surge woman is of two worlds: pixel and pen, URL and IRL. Through a bundle of ecosystem perks, the Surge Passport is a golden ticket into Web3. Each feature of the art, though hand-sketched, has been layered algorithmically to form a whole. The Surge Passport collection represents our belief that beautiful things have a human touch.',
  surgePassportNFT: 'Surge Passport NFT',
  surgeURL: 'https://surgewomen.io',
  targetAudience: 'The Surge Passport NFT is the <strong>perfect gift</strong> for people who want to get into crypto, but don\'t know where to begin.',
  team: 'Team',
  terms: 'Terms, Conditions and Disclosures',
  termsUrl: 'https://www.surgewomen.io/terms-conditions',
  walletNotConnected: 'Your wallet was not connected succesfully',
  howDoI: 'how do I',
  wait: 'Wait, ',
  whatIsMinting: 'What is minting?',
  whoops: 'Whoops!'
};
